### ISSUE TITLE
some doubts about the generalization performance on Make3D dataset

### ISSUE THREAD

**Issue by seanM29** [sshan-zhao/GASDA#1]
In section 4.3, paper says "although the domain shift between Make3D and KITTI is large", so the model is trained on really kitti or vkitti data?
besides, the paper focus on Symmetric Domain Adaptation, it seems no component of network try to solve really data set domain adaptation, so why is the performance  so good on make3d data set when network is trained on kiiti/vkitti data?
Thank you for sharing results of your work.
This is a really impressive paper and your response is appreciated.

**Comment by sshan-zhao** [comment]
Hi, 
Thanks for your interest.
a) The model, evaluated on Make3D, is trained on real stereo data and labeled vkitti data. Actually, that is our final model.
b) This work mainly focuses on the adaptation between synthetic data and real data. I believe the method could be also used to solve the adaptation between real domains (like, kitti, make3d, cityscapes, etc.). Our method just performs better than those only trained on kitti or using domain adaptation, but worse than those trained on Make3D.
