### ISSUE TITLE
ResNetFeatGenerator

### ISSUE THREAD

**Issue by BIGWangYuDong** [sshan-zhao/GASDA#10]
https://github.com/sshan-zhao/GASDA/blob/87a2276054a966e41084165832c23c40bf75f791/models/networks.py#L127

where can i find the classes  ResNetFeatGenerator()

**Comment by sshan-zhao** [comment]
> https://github.com/sshan-zhao/GASDA/blob/87a2276054a966e41084165832c23c40bf75f791/models/networks.py#L127
> 
> where can i find the classes ResNetFeatGenerator()

This part is useless, and I have deprecated it. I will delete it.

**Comment by BIGWangYuDong** [comment]
> > https://github.com/sshan-zhao/GASDA/blob/87a2276054a966e41084165832c23c40bf75f791/models/networks.py#L127
> > 
> > where can i find the classes ResNetFeatGenerator()
> 
> This part is useless, and I have deprecated it. I will delete it.
