### ISSUE TITLE
how to evaluation on Make3D dataset

### ISSUE THREAD

**Issue by jdk9405** [sshan-zhao/GASDA#2]
I read your paper very impressively! and I have a question.
In table 4, you have measured the metric for the Make3D dataset.
But it's depth map label does not match the size of the original image so I wonder how to evaluate it. (crop, resize, interpolation, etc)
I would really appreciate if you let me know how it works. THANK YOU.

**Comment by sshan-zhao** [comment]
Hi, 
Thanks for your interest!
The operation we used is similar to that in Godard et al., i.e., resize and then central crop.

**Comment by koutilya-pnvr** [comment]
What are the final dimensions of the RGB and depth images after resizing and cropping?
