### ISSUE TITLE
can‘t download pretrained model

### ISSUE THREAD

**Issue by chenglong0313** [sshan-zhao/GASDA#3]
Are there any other way to download models weights.
Something went wrong with the onedrive link.

**Comment by sshan-zhao** [comment]
> Are there any other way to download models weights.
> Something went wrong with the onedrive link.

You cannot access the onedrive or the provided link is wrong (actually I have tested it and there seems to be no problem)? Can you provide the error information?

**Comment by chenglong0313** [comment]
> > Are there any other way to download models weights.
> > Something went wrong with the onedrive link.
> 
> You cannot access the onedrive or the provided link is wrong (actually I have tested it and there seems to be no problem)? Can you provide the error information?

I can access onedrive , but can't open the provided link.
the error always shows   "Something went wrong, please try again or refresh the page."

**Comment by sshan-zhao** [comment]
> > > Are there any other way to download models weights.
> > > Something went wrong with the onedrive link.
> > 
> > 
> > You cannot access the onedrive or the provided link is wrong (actually I have tested it and there seems to be no problem)? Can you provide the error information?
> 
> I can access onedrive , but can't open the provided link.
> the error always shows "Something went wrong, please try again or refresh the page."

I don't know the reason, but I will upload the models to the google drive.

**Comment by chenglong0313** [comment]
> > > > Are there any other way to download models weights.
> > > > Something went wrong with the onedrive link.
> > > 
> > > 
> > > You cannot access the onedrive or the provided link is wrong (actually I have tested it and there seems to be no problem)? Can you provide the error information?
> > 
> > 
> > I can access onedrive , but can't open the provided link.
> > the error always shows "Something went wrong, please try again or refresh the page."
> 
> I don't know the reason, but I will upload the models to the google drive.

ok. look forward to your available  model.  thanks a lot.

**Comment by sshan-zhao** [comment]
> > > > > Are there any other way to download models weights.
> > > > > Something went wrong with the onedrive link.
> > > > 
> > > > 
> > > > You cannot access the onedrive or the provided link is wrong (actually I have tested it and there seems to be no problem)? Can you provide the error information?
> > > 
> > > 
> > > I can access onedrive , but can't open the provided link.
> > > the error always shows "Something went wrong, please try again or refresh the page."
> > 
> > 
> > I don't know the reason, but I will upload the models to the google drive.
> 
> ok. look forward to your available model. thanks a lot.

Hi, try this link:
https://drive.google.com/open?id=1CvuGUTObRhpZpSTYxy-BIRhft6ttMJOP

**Comment by chenglong0313** [comment]
> > > > > > Are there any other way to download models weights.
> > > > > > Something went wrong with the onedrive link.
> > > > > 
> > > > > 
> > > > > You cannot access the onedrive or the provided link is wrong (actually I have tested it and there seems to be no problem)? Can you provide the error information?
> > > > 
> > > > 
> > > > I can access onedrive , but can't open the provided link.
> > > > the error always shows "Something went wrong, please try again or refresh the page."
> > > 
> > > 
> > > I don't know the reason, but I will upload the models to the google drive.
> > 
> > 
> > ok. look forward to your available model. thanks a lot.
> 
> Hi, try this link:
> https://drive.google.com/open?id=1CvuGUTObRhpZpSTYxy-BIRhft6ttMJOP

thanks a lot.  This link is ok.
