### ISSUE TITLE
Regarding Ground truth for Kitti dataset

### ISSUE THREAD

**Issue by koutilya-pnvr** [sshan-zhao/GASDA#4]
https://github.com/sshan-zhao/GASDA/blob/2835031eae5beb8e26f7323c4c02e7643a830d2e/utils/dataset_util.py#L111

Why did you choose to build your own ground truth for Kitti dataset when you have the ground truth data available inherently in the [official Kitti dataset](http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction).

**Comment by sshan-zhao** [comment]
> https://github.com/sshan-zhao/GASDA/blob/2835031eae5beb8e26f7323c4c02e7643a830d2e/utils/dataset_util.py#L111
> 
> Why did you choose to build your own ground truth for Kitti dataset when you have the ground truth data available inherently in the [official Kitti dataset](http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction).

Hi,
Firstly, our evaluation strategy is the same as [Godard et.al](https://github.com/mrharicot/monodepth), and the training/validation/test splits might be different from [the official](http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction). Secondly, actually the official ground truth is obtained by fusing the lidar data of multiple frames and correcting the depth via SGM, so I think the official ground truth is not quite different from the raw lidar data, but denser. As a result, I think it will not affect the final evaluation results. Thanks.

**Comment by koutilya-pnvr** [comment]
Fair enough. Thanks a lot for your response.
